service: benvp

image: benvp/website

servers:
  - s03.benvp.co

ssh:
  user: benvp

registry:
  server: ghcr.io
  username: benvp
  password:
    - MRSK_REGISTRY_PASSWORD

env:
  clear:
    PORT: 3000
    PHX_HOST: benvp.co
    NOTION_MEDIA_DIR: /app/media
  secret:
    - SECRET_KEY_BASE
    - NOTION_ACCESS_TOKEN
    - NOTION_BLOG_DATABASE_ID

builder:
  args:
    NOTION_MEDIA_DIR: /app/media
  remote:
    arch: amd64
    host: ssh://benvp@s03.benvp.co

volumes:
  - "/storage/benvp/media:/app/media"


healthcheck:
  path: /healthz
  interval: 30s
  max_attempts: 10

labels:
  traefik.http.routers.benvp.rule: Host(`benvp.co`)
  traefik.http.routers.benvp_secure.entrypoints: websecure
  traefik.http.routers.benvp_secure.rule: Host(`benvp.co`)
  traefik.http.routers.benvp_secure.tls.certresolver: letsencrypt

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    entryPoints.websecure.address: ":443"
    certificatesResolvers.letsencrypt.acme.email: "hi@benvp.co"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
